project:
  type: website
  render:
    - index.qmd
    - presentations_and_publications/momo/index.qmd
    - presentations_and_publications/homework/homework.qmd
    - presentations_and_publications/paper/my_first_model.qmd
    - presentations_and_publications/paper/supplemental_materials.qmd
  # render for gh-pages
  output-dir: docs

website:
  title: "My First Four-Step Model"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true