---
title: "My First Four-Step Model: a Simple and Accessible Tool to Teach Travel Demand Modeling"
author:
  - name: Matthew Wigginton Bhagat-Conway
    affiliations:
      - name: University of North Carolina at Chapel Hill
        department: Department of City and Regional Planning
        address: "223 E Cameron Ave, CB #3140"
        city: Chapel Hill
        state: NC
        country: USA
        postal-code: 27599
    orcid: 0000-0002-1210-2982
    email: mwbc@unc.edu
abstract: |
  abstract
keywords: [travel demand modeling, teaching, education, open-source]
bibliography: bibliography.bib
format: trb-pdf
date: 2024-06-05
execute:
    eval: true
    echo: true
    output: true
    cache: true
fig-dpi: 300
---

# Introduction

The four-step travel demand model is ubiquitous in transportation planning. It was one of the earliest travel demand models developed [@weiner_urban_2013;@federalhighwayadministration_planpac_1977]. While it has come under significant criticism lately [@mladenovic_shortcomings_2014], it remains in common use. Many large regions have transitioned to more modern activity-based models, but many smaller regions and even some large regions continue to use the four-step model.

Most transportation programs in both planning and engineering cover travel demand modeling at least to some extent [@zhou_transportation_2009]. However, in my experience, it is almost invariably taught in a "bottom-up" approach. Students take classes on transportation planning, econometrics, choice modeling, and programming. Students then work with individual components of demand models, such as a trip generation or mode choice model. Often, students never "put it all together" to run a regional model from start to finish. The vast majority of learning time is spent on theory and mathematics, rather than applications.

The theory and mathematics are paramount for those who will build and run travel demand models themselves. This is a very small group of students, however, especially in planning. At most metropolitan planning organizations and DOT's, demand models are estimated and run either by consultants or a small in-house team. However, consumers of model output are a much larger group: transportation planners, land use planners, developers, advocates, and so on. For this larger group, only a cursory understanding of the mathematics is required; understanding the general mechanisms and assumptions the model relies on is far more important. A better understanding of modeling among this group will help promote better communications between modelers and model consumers. Consumers will be more aware of what the model can and can't do, and more able to come up with situations where the model may be helpful. Understanding will also promote a "healthy skepticism" of the model, enabling feedback from users on the model and ultimately leading to better models and decision support.

In this article, I propose a "top-down" approach to teaching modeling. In this approach, the first step is a very high-level discussion of the steps in the four-step model, followed immediately by students actually running a complete (albeit simplified) four-step model, and interpreting the output. Students interested in  may take further classes, but all students will have some first-hand experience with demand models---something many students do net get at all today, even after taking many classes on modeling.

To facilitate teaching in this way, I introduce the "My First Four Step Model" R package, a very simple four-step model that can run quickly on typical consumer-grade computers without complex software dependency installation processes or expensive licensing. It can be estimated for any US metropolitan area using only publicly-available data. The goal of the package is to enable a much broader swath of planners and engineers to work with a travel demand model during their education. I use the package in my Introduction to Planning Methods course, where we spend only a week discussing transportation modeling and engineering, and at the conclusion the students run a simple demand model and future scenario for the Research Triangle region of North Carolina. This article discusses the model structure and implementation and how I use it in the classroom. In the penultimate section, I provide a complete example including R code for estimating and running the model.

# Literature review

There is very little literature on pedagogical practices surrounding travel demand modeling. Most transportation planning and engineering programs cover the topic [@zhou_transportation_2009], but it was not even included on a semi-regular survey of transportation faculty regarding what they consider the most important topics in introductory courses [@turochy_structuring_2013].

Simulation of real-world activities has a centuries-long history in education, starting in the medical field, with positive outcomes for student learning [@mcgaghie_critical_2010]. Simulation activities are widely used in transportation engineering instruction [@hurwitz_transportation_2015], and research on active learning techniques in transportation engineering goes back decades [@weir_active_2004]. Simulation activities in planning have a similarly long history [e.g., @meier_gaming_1966].

Effective simulations as an eductational tool often take the form of a game. Solving transportation challenges is one of the recurrent examples in the foundational book on gamification in education, Clark Abt's _Serious Games_ [@abt_serious_1970]. More recently, physical board games have been used to teach transportation planning using both popular-press games [@huang_game_2012] and purpose-built educational games [@paget-seekins_transform_2021].

Computer-based simulations have rapidly become ubiquitous in transportation engineering education [@hurwitz_transportation_2015]. Liao, Liu, and Levinson [-@liao_simulating_2009] built a web-based traffic simulation tool to help students experiment with signal timing practices. The interactive A/B Street traffic-simulation software has likewise been used in undergraduate courses at Arizona State University [@carlino_street_2024]. An economic simulation of airline operations has also been applied to help budding engineers understand airline operations [@luken_case_2011].

Computer-based simulations have also been applied in planning, although perhaps less frequently. Simulations in planning classrooms often take the form of commercial planning games, such as SimCity or Cities: Skylines [@gaber_simulating_2007;@khan_perceptions_2021], likely due to less funding for purpose-built simulations in planning as opposed to engineering. A significant challenge with commercial games is that they are intended primarily for entertainment, and thus may oversimplify or even modify system dynamics to support enjoyable gameplay rather than educational outcomes [@gaber_simulating_2007;@walker_did_2009]. The advantage, of course, is that commercial games are more likely to receive significant upfront investment as well as continued support, a significant problem with games developed for educational purposes [@sobke_two_2018].

Public education and communication are another arena of planning where gamification and simulation have been deployed. The _Future Energy Chicago_ exhibit at Chicago's Museum of Science and Industry engages participants in a several-hour, facilitated game to improve energy outcomes. Survey data suggests that the game improved some aspects of willingness to conserve energy [@applebaum_collaboration_2021]. The CityScope platform provides a hands-on physical environment wherein members of the public can make land-use changes to a Lego model of a neighborhood and see computer simulation output regarding transport and energy consumption in real time [@alonso_cityscope_2018]. The CoAXs platform allowed to see how proposed Bus Rapid Transit routes would affect their ability and the ability of other citizens to reach key destinations, and was found to support improved learning and discussion outcomes among participants [@stewart_coaxs_2016;@stewart_mapping_2017]. All of these simulations are perforce somewhat simpler than might be used in a classroom environment, since they target the general public rather than future practitioners.

Teaching travel demand modeling differs from other places where simulations have been deployed in transportation education. Travel demand models are themselves simulations of complex urban systems. Applying them in a classroom environment does not demand developing a new simulation. Rather, it means simplifying the existing structure of demand models to create one suitable for students with only a rudimentary understanding of the theory and mathematics involved.

The only travel demand modeling software designed specifically for education I am aware of is the now-defunct ADAM project [@zhu_enhancing_2011], which implemented a simple agent-based model for transportation education. This model was primarily a network assignment model for simple networks; it started with production (workers) and attractions (jobs), and the task was to modify the network to reduce congestion. The software included a simple network editor, and was deployed as a Java applet which at the time was widely accessible (though Java applets are now obsolete). Likely due to computational limits in place at the time, it worked with a very simple network of only 24 nodes and 34 bidirectional links.

# My first four-step model

My First Four-Step Model is a software package designed to allow students with minimal experience and consumer-grade computer hardware to run a simple four-step travel demand model. It is implemented as an R package [@r_2024], which has several advantages. R is a free, open-source, and cross-platform statistical programming language, allowing students to run it on their own computers regardless of software configuration. Furthermore, R is becoming the _lingua franca_ of quantitative urban planning. Using the My First Four Step Model package in an assignment gives students a gentle introduction to the language and potentially piques their interest in learning more. The package has several key design goals:

1. The four steps of the model should map directly onto four functions in the package;
1. Simplicity is paramount—there should not be any additional steps or complexity (e.g. university models, airport models, etc.);
1. It should be able to be estimated for any location in the United States using only publicly-available data;
1. There should be intuitive tools to visualize model inputs, outputs, and parameters, so students can interpret them and understand how the model works;
1. Preparing land-use and transportation scenarios should be simple;
1. It should run on any computer a student is likely to have—Windows, Mac, Linux, or Chromebook, old or new, cheap or expensive; and
1. It should depend only on R itself and common R packages that are easily installed on all platforms from the Comprehensive R Archive Network (CRAN).

The package is available on Github at [https://github.com/mattwigway/MyFirstFourStepModel](https://github.com/mattwigway/MyFirstFourStepModel), and is licensed under an MIT license. In the sections below, I discuss how I implement the model in the classroom environment (including complete code to run the model), then turn to the estimation processes and technical details of the model.

## Implementation in the classroom

I use the package in my Planning Methods course in the Department of City and Regional Planning at the University of North Carolina at Chapel Hill. This is an introductory master's level course which all planning students (not only those in transportation) take, generally during their first semester. In the course, I spend a week discussing 

## Model architecture and input data

The model is a completely vanilla, classical four-step model, consisting of trip generation, distribution, mode choice, and network assignment. There are no auxiliary models (e.g. freight, airport, or out-of-region trips), though there is a trivial population synthesis step embedded in the trip generation step.

The entire model process is implemented in R [@r_2024] for ease of use and portability, with each step of the four-step model contained within a single function. For performance, some input data preparation is done using Julia [@bezanson_julia_2017], but Julia is not required to run the model itself. In practice, this means students using the model will need to install R, but not Julia.

The sections that follow describe each of the four steps of the model, and detail the data sources and specific model architectures used.

### Trip generation

Trip generation is based on the 2017 National Household Travel Survey [NHTS; @NHTS_2017]. The model divides the day into four time periods: overnight (7:00 pm--5:59 am), AM Peak (6:00 am--9:59 am), midday (10:00 am--3:59 pm), and PM Peak (4:00 pm--6:59 pm). The model also divides trips into three purposes: home-based work (HBW), home-based other (HBO), and non-home-based (NHB). While this is somewhat fewer trip types and time periods than might be included in production travel models, it is consistent with the general practice of dividing trips by time of day and count.

Household-level trip counts are estimated for each time period and trip type using a simple linear regression with the trip count as the dependent variable and independent variables for number of vehicles, household size, household income, Census tract residential density, and number of workers. This results in 12 regression equations, for each time period and trip purpose. Household income is represented by dummy variables for less than $35,000, $35,000–$74,999, $75,000–$99,999, and $100,000 or more.

Simple linear regression is used rather than traditional cross-classification or more complex regression methods because of its ease of interpretation. I teach my basic unit on demand modeling shortly after teaching regression, and applying regression here provides a real-world example for students. I present the regression models to the students for practice interpreting regression outputs. It also allows students to better understand what is going on under the hood of the model, without teaching a new technique that would primarily be useful for students who are actually planning to become modelers (and, presumably, will take more advanced modeling classes).

The trip generation regressions can be estimated either for the full NHTS, or a subset more relevant to the region at hand. For my in-class exercise using a model of the Research Triangle region, I use the XX household records in North Carolina as the estimation sample. This provides a reasonable balance between locally-relevant travel patterns and sample size.

The model is an aggregate model, and when used for forecasting we do not have household-level data. Instead we have marginal data at the TAZ level. For simplicity and to make the model easily compatible with Census data, TAZ's directly correspond to Census tracts. The model expects marginals for household size (topcoded at 4), number of workers (topcoded at 3), number of vehicles (topcoded at 3), and income (in the categories used in the regression). 

For forecasting, TAZ-level demographics are specified via a simple Excel format. The format for demographic data is shown in @tbl-demographic-scenario for a single TAZ/Census tract. The Census tract is presented in the first column. Each marginal value is presented in a separate row, with the name of the marginal (`hhsize`, `income`, `vehicles`, or `workers`) in one column, the value (e.g. `1` for one-person households), and the number of households in that category in that tract. For baseline years, this data is easily retrieved from the five-year American Community Survey. For future years, a variety of statistical and GIS tools can be used to generate files in the appropriate format.

|  `geoid`      | `marginal` | `value` | `count` |
|:------------|:-------|--:|---:|
| 37183053411 | `hhsize` | 1 | 514 |
| 37183053411 | `hhsize` | 2 | 711 |
| 37183053411 | `hhsize` | 3 | 940 |
| 37183053411 | `hhsize` | 4 | 1907 |
| 37183053411 | `income` | 0 | 358 |
| 37183053411 | `income` | 35000 | 595 |
| 37183053411 | `income` | 75000 | 183 |
| 37183053411 | `income` | 100000 | 2936 |
| 37183053411 | `vehicles` | 0 | 110 |
| 37183053411 | `vehicles` | 1 | 921 |
| 37183053411 | `vehicles` | 2 | 2089 |
| 37183053411 | `vehicles` | 3 | 952 |
| 37183053411 | `workers` | 0 | 288 |
| 37183053411 | `workers` | 1 | 1784 |
| 37183053411 | `workers` | 2 | 1711 |
| 37183053411 | `workers` | 3 | 289 |

: Specification of a demographic scenario {#tbl-demographic-scenario}

To apply the household-level model to this aggregate data, I disaggregate the data to household-level records (i.e. a synthetic population) using iterative proportional fitting with a seed matrix derived from the Integrated Public Use Microdata Sample 2021 Five-Year American Community Survey data for the entire US [@ruggles_ipums_2024]. This seed matrix is precalculated and ships with the software. The regression equations are then used to predict household-level tripmaking, which is then re-aggregated to the tract level.

<!--# The readme says we then disaggregate to higher numbers of vehicles, workers, household members using the unconditional distribution from the PUMS. It looks like we don't actually do that based on the source code. -->

Trip attraction is somewhat more complicated, as the NHTS does not provide sufficient spatial detail to know where trips go. Instead, we use the Puget Sound Household Travel Survey, which includes origin and destination Census tract in the public-use dataset [@PSRC_Household_Travel_Survey]. I calculate the total number of home-based work and home-based other trips in each time period that have the non-home end in each Census tract in the Puget Sound region. I also calculate half the number of non-home-based trips in each time period that have either end in each tract (we divide by two to correctly reproduce the total number of non-home-based trips).

To extrapolate this data to tracts outside the region, I build linear regression models for each trip type and time period based on total employment and employment in retail, education, and accomodation/food services from the US Census Bureau Longitudinal Employer-Household Dynamics Origin-Destination Employment Statistics. For future-year scenarios, employment in each tract in each of these categories must be predicted, and supplied in a similar format to @tbl-demographic-scenario. Since the trip production model is likely to be more accurate, I balance total attractions by trip type in each time period to match estimated productions.

### Trip distribution

The trip distribution step uses a singly-constrained (at the production end) gravity model, of the form
$$
t_{ijpc} = P_{ipc} \frac{A_{jpc} d_{ij}^{\beta_c}}{\displaystyle\sum_{j'} A_{j'pc} d_{ij'}^{\beta_c}}
$$
where $t_{ijpc}$ is the total number of trips of type $c$ (home-based work, home-based other, or non-home-based) from TAZ $i$ to $j$ during time period $p$. $P_{ipc}$ is the total trips of type $c$ produced in TAZ $i$ during timne period $p$, and $A_{jpc}$ is the total trips attracted to TAZ $j$. $\beta_c$ is the decay parameter for trip type $c$; the decay parameter is expected to be negative, and differs by trip type but not time period (though the spatial distribution of productions and attractions does vary by time period.) $d_{ij}$ is the crow-flies distance from the TAZ $i$ to TAZ $j$.

$\beta_c$ is calibrated for each trip type using the method introduced by Merlin [-@merlin_new_2020] based on the median trip length. The method observes that half of the weighted destinations should be closer to the origin than the median trip, and half should be further away. The parameter is calibrated using Brent's method to solve the problem^[This is slightly different than the function presented in Merlin [-@merlin_new_2020]. It divides by total weighted destinations to make the function have a single minimum; otherwise $\beta = -\infty$ is also a minimum as the total weighted destinations are zero. I replace the absolute value with squaring to make the derivative continuous at the optimal value.]
$$
\displaystyle\min_\beta \left(\frac{\displaystyle\sum_{i, j, d_{ij} < \tilde d} P_i A_j d_{ij}^\beta - \displaystyle\sum_{i, j, d_{ij} \geq \tilde d} P_i A_j d_{ij}^\beta}{\displaystyle\sum_{i, j} P_i A_j d_{ij}^\beta}\right)^2
$$
where $\tilde d$ is the median trip distance for the trip type under consideration (subscript $c$ suppressed for readability), and other variables are as defined previously.

The median trip distance is derived from the NHTS, or a subsample more relevant to the region being modeled. Since the NHTS reports network rather than crow-flies distance, we approximate the crow-flies distance for each NHTS trip by dividing the network distance by $\sqrt{2}$. <!--# or just use network distance? that might be easier than justifying sqrt(2) -->

For intrazonal trips, we assume a travel distance of $0.52 \sqrt{s}$, where $s$ is the area of the TAZ. This is based on a Monte Carlo simulation of the average distance between random points in a square. There are two opposing factors that bias this, which should somewhat cancel out. TAZ's are not square, and are less compact than a square, which increases average travel distance. However, development within a TAZ is also concentrated in certain areas, which decreases average travel distance.

### Mode choice

The mode choice model is a simple multinomial logit model estimated based on the NHTS. Because we do not have detailed information about each trip and the alternatives available in the NHTS, the model is based solely on trip type, time period, travel distance, and housing unit density in the home tract. For non-home-based trips, a separate model is estimated excluding housing unit density. Goodness of fit is expected to be poor, but the point of the model is to demonstrate the simplest possible demand model, not to produce a highly accurate forecasting system. In theory it would be possible to include household characteristics, since trip productions are modeled using a disaggregate model. However, this would complicate the model system and defeat the purpose of building the simplest possible model for teaching purposes.

### Network assignment

The network assignment uses a Frank-Wolfe static traffic assignment algorithm [@ortuzar_modelling_2011]. Impedances are based on a Bureau of Public Roads-style function:
$$
t_{\mathrm{congested}} = \left(1 + 0.6 \left[\frac{f}{c}\right] ^ 5 \right) t_{\mathrm{freeflow}} 
$$
where $f$ is the predicted flow, $c$ is the link capacity, and $t_{\mathrm{congested}}$ and $t_\mathrm{freeflow}$ are congested and free-flow link travel times. The factors 0.6 and 5 are derived from the Southern California Association of Governments travel demand model [@southerncaliforniaassociationofgovernments_scag_2012].

The assignment algorithm is written in pure R. This is quite slow, but will run anywhere R does—an advantage when the model will be run on students' computers. For this reason, networks need to be simple, and regions small. In the example below, I use only the central three counties of the Research Triangle region. I derive the network from OpenStreetMap, and retain only motorways, trunk, and primary roads (and associated ramps).

## Estimation for a new region

# Discussion and conclusion

A key limitation of this research is that travel demand modeling was not covered in our introductory Planning Methods course at all prior to introducing the My First Four Step Model package, so I was not able to evaluate how student learning outcomes changed. Though the exercises with the model were generally well received, I did not do any formal evaluation of student perspectives.

# References