---
title: Estimate RDU
author: Matt Bhagat-Conway
---

Estimate and save a four-step model for the Research Triangle region.

```{r}
devtools::load_all()
library(readr)
library(igraph)
library(sf)
```

```{r}
nhts = load_nhts(here::here("data/nhts"))
nhts$households = filter(nhts$households, HHSTATE=="NC")
```

```{r}
seed_matrix = read_csv(here::here("seed_matrix.csv"))
```

```{r}
psrc = read_csv(here::here("data/psrc_trips.csv"), col_types=cols(o_tract10=col_character(), d_tract10=col_character()))
psrc_lodes = read_csv(here::here("data/lodes/wa_wac_S000_JT00_2019.csv.gz"))
```

```{r}
base_marginals = get_base_marginals("NC", c("Buncombe"), 2021)
```

```{r}
network = read_graph("data/osm/triangle.graphml", format="graphml")
network_geo = read_sf("data/osm/triangle.gpkg")
```

```{r}
model = estimate(nhts, seed_matrix, psrc, psrc_lodes, base_marginals, network, network_geo)
```

```{r}
save_model(model, "rdu.model")
```

```{r}
save_landuse_scenario(base_marginals, "RDU Baseline.xlsx")
```