#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr cross_join
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr group_by
#' @importFrom dplyr group_map
#' @importFrom dplyr group_modify
#' @importFrom dplyr inner_join
#' @importFrom dplyr last
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr summarize
#' @importFrom dplyr ungroup
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 ggplot
#' @importFrom Hmisc wtd.quantile
#' @importFrom igraph all_shortest_paths
#' @importFrom igraph ecount
#' @importFrom igraph edge_attr
#' @importFrom igraph get.edge.ids
#' @importFrom igraph shortest_paths
#' @importFrom igraph vertex_attr
#' @importFrom magrittr %>%
#' @importFrom nnet multinom
#' @importFrom purrr list_rbind
#' @importFrom readr col_double
#' @importFrom readr col_integer
#' @importFrom readr cols_only
#' @importFrom readr read_csv
#' @importFrom readxl read_excel
#' @importFrom sf st_as_sf
#' @importFrom sf st_distance
#' @importFrom sf st_transform
#' @importFrom stringr str_to_lower
#' @importFrom tibble as_tibble
#' @importFrom tibble tibble
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyselect contains
#' @importFrom writexl write_xlsx
## usethis namespace: end
NULL
