# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_MyFirstFourStepModel_wrappers", use_symbols = TRUE, package_name = "MyFirstFourStepModel")

#' @usage NULL
#' @useDynLib MyFirstFourStepModel, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
update_flows <- function(edge_flows, flows_to_node, predecessor, incoming_edge, origin) .Call(wrap__update_flows, edge_flows, flows_to_node, predecessor, incoming_edge, origin)


# nolint end
