#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_match
#' @importFrom dplyr case_when
#' @importFrom dplyr cross_join
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr group_by
#' @importFrom dplyr group_map
#' @importFrom dplyr group_modify
#' @importFrom dplyr inner_join
#' @importFrom dplyr last
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr summarize
#' @importFrom dplyr ungroup
#' @importFrom fs file_delete
#' @importFrom fs file_temp
#' @importFrom fs path_package
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_sf
#' @importFrom ggplot2 geom_sf_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 position_nudge
#' @importFrom ggplot2 scale_fill_fermenter
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_minimal
#' @importFrom glue glue
#' @importFrom Hmisc wtd.quantile
#' @importFrom igraph all_shortest_paths
#' @importFrom igraph E
#' @importFrom igraph E<-
#' @importFrom igraph ecount
#' @importFrom igraph edge_attr
#' @importFrom igraph get.edge.ids
#' @importFrom igraph read_graph
#' @importFrom igraph shortest_paths
#' @importFrom igraph subgraph
#' @importFrom igraph V
#' @importFrom igraph vertex_attr
#' @importFrom JuliaCall julia_setup
#' @importFrom magrittr %>%
#' @importFrom nnet multinom
#' @importFrom purrr list_rbind
#' @importFrom purrr map
#' @importFrom readr col_character
#' @importFrom readr col_double
#' @importFrom readr col_integer
#' @importFrom readr cols
#' @importFrom readr cols_only
#' @importFrom readr read_csv
#' @importFrom readxl read_excel
#' @importFrom rnaturalearth ne_download
#' @importFrom sf read_sf
#' @importFrom sf st_as_sf
#' @importFrom sf st_buffer
#' @importFrom sf st_crs
#' @importFrom sf st_distance
#' @importFrom sf st_join
#' @importFrom sf st_transform
#' @importFrom sf write_sf
#' @importFrom stringr str_starts
#' @importFrom stringr str_to_lower
#' @importFrom tibble as_tibble
#' @importFrom tibble tibble
#' @importFrom tibble tribble
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyselect contains
#' @importFrom writexl write_xlsx
## usethis namespace: end
NULL

#' @export
tibble::tribble
